# Generated by Django 4.2.2 on 2023-08-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('containerID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FoodConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('containerID', models.CharField(max_length=100)),
                ('lvlMax', models.IntegerField(default=1000)),
                ('lvlThresholdStart', models.IntegerField(default=300)),
                ('lvlThresholdStop', models.IntegerField(default=700)),
                ('lvlMin', models.IntegerField(verbose_name=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('hatchId', models.CharField(max_length=100)),
                ('direction_Trigger', models.CharField(choices=[(0, 'Nothing'), (1, 'Inside'), (2, 'Outside')], default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HatchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hatchId', models.CharField(max_length=100)),
                ('allowOpen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('petID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HeartBeatConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petID', models.CharField(max_length=100)),
                ('high_Threshold', models.IntegerField(default=200)),
                ('low_Threshold', models.IntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='LiveClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeId', models.IntegerField()),
                ('nodeCoapName', models.CharField(default='', max_length=16)),
                ('nodeCoapAddress', models.CharField(default='', max_length=30)),
                ('isFree', models.BooleanField(default=True)),
                ('nodeType', models.CharField(choices=[(0, 'unknown'), (1, 'food'), (2, 'heartbeat'), (3, 'hatch')], default=0, max_length=10)),
                ('isActuator', models.BooleanField(default=False)),
                ('lastInteraction', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeIdMQTT', models.IntegerField()),
                ('nodeIdCOAP', models.IntegerField()),
            ],
        ),
    ]
