# Generated by Django 4.2.2 on 2023-08-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Network_Controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hatch',
            name='direction_Trigger',
            field=models.CharField(choices=[('Nothing', 'Nothing'), ('Inside', 'Inside'), ('Outside', 'Outside')], default='Nothing', max_length=10),
        ),
        migrations.AlterField(
            model_name='hatch',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='heartbeat',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='liveclient',
            name='lastInteraction',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='liveclient',
            name='nodeType',
            field=models.CharField(choices=[(0, 'unknown'), (1, 'food'), (2, 'heartbeat'), (3, 'hatch')], default='unknown', max_length=10),
        ),
    ]
