# Generated by Django 4.2.2 on 2023-08-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Network_Controller', '0002_alter_food_time_alter_hatch_direction_trigger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclient',
            name='nodeType',
            field=models.CharField(choices=[('unknown', 'unknown'), ('food', 'food'), ('heartbeat', 'heartbeat'), ('hatch', 'hatch')], default='unknown', max_length=10),
        ),
    ]
