# Generated by Django 4.2.2 on 2023-09-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Network_Controller', '0004_alter_foodconfig_lvlmin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveclient',
            name='nodeCoapName',
        ),
    ]
